// CLASS MUST BE LOCATED IN android.print PACKAGE
// BECAUSE IT USE PrintDocumentAdapter.LayoutResultCallback CLASS
package android.print

import android.content.Context
import android.os.CancellationSignal
import android.os.ParcelFileDescriptor
import java.io.File


/**
 * Assistant which create PDF file from WebView bitmap.
 *
 * Located in android.print package because use PrintDocumentAdapter.LayoutResultCallback class
 * which is package-private
 *
 * @param context Activity or context which use PdfPrint
 * @param printAttributes size of PDF format and margins
 */
class PdfPrint (private val context: Context, private val printAttributes: PrintAttributes) {


    /**
     * Use PrintDocumentAdapter to copy bytemap from WebView and make PDF from it
     *
     * @param printAdapter PrintDocumentAdapter generated by WebView which shows HTML
     * @param fileName Name of file which will be created
     */
    //COPY BYTEMAP FROM PrintDocumentAdapter CREATED BY WEBVIEW TO FILE
    fun write (printAdapter: PrintDocumentAdapter, fileName: String) {
        printAdapter.onLayout(null, printAttributes, null,
            object : PrintDocumentAdapter.LayoutResultCallback() {
                override fun onLayoutFinished(info: PrintDocumentInfo?, changed: Boolean) {
                    printAdapter.onWrite(arrayOf(PageRange.ALL_PAGES),
                        getOutputFile(fileName),
                        CancellationSignal(),
                        object : PrintDocumentAdapter.WriteResultCallback() {
                            override fun onWriteCancelled() {
                                super.onWriteCancelled()
                            }
                        })
                }
            }, null)
    }

    /**
     * Creates new file if it not exists
     *
     * @param fileName name of created file
     * @return Descriptor of created file
     */
    private fun getOutputFile(fileName: String) : ParcelFileDescriptor {

        //CREATE EMPTY PDF FILE
        val file = File(context.filesDir, fileName)
        file.createNewFile()

        //RETURN DESCRIPTOR OF EMPTY PDF FILE
        return ParcelFileDescriptor.open(file, ParcelFileDescriptor.MODE_READ_WRITE)


    }

}